printWidth: 80
tabWidth: 2
useTabs: false
semi: true
singleQuote: true
trailingComma: all
bracketSpacing: true
jsxSingleQuote: false
arrowParents: always
proseWrap: never
htmlWhitespaceSensitivity: strict
endOfLine: lf
